global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'core_microservice'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: 'core'

  - job_name: 'auth_microservice'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3001']
        labels:
          service: 'auth'